//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFConsoleServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DictionaryOnTask
    {
        public int Server_id { get; set; }
        public int Project_id { get; set; }
        public int Task_id { get; set; }
        public int Dictionary_id { get; set; }
        public System.DateTime DateAdded { get; set; }
        public System.DateTime DateSync { get; set; }
        public Nullable<System.DateTime> DateDel { get; set; }
        public int DictionaryOnTask_id { get; set; }
    
        public virtual Dictionary Dictionary { get; set; }
        public virtual Task Task { get; set; }
    }
}
