//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFConsoleServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPermission
    {
        public int UserPermission_id { get; set; }
        public int User_id { get; set; }
        public int Permission_id { get; set; }
        public int Give_User_id { get; set; }
        public Nullable<int> Remove_User_id { get; set; }
        public Nullable<System.DateTime> DateDel { get; set; }
        public System.DateTime DateAdded { get; set; }
    
        public virtual Permission Permission { get; set; }
        public virtual User User { get; set; }
    }
}
