//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFConsoleServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserChangeHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserChangeHistory()
        {
            this.DictionaryChangeHistories = new HashSet<DictionaryChangeHistory>();
            this.Queues = new HashSet<Queue>();
        }
    
        public int UserHistory_id { get; set; }
        public int User_id { get; set; }
        public int Dictionary_id { get; set; }
        public int Action_id { get; set; }
        public System.DateTime DateHistory { get; set; }
    
        public virtual ActionType ActionType { get; set; }
        public virtual Dictionary Dictionary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DictionaryChangeHistory> DictionaryChangeHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Queue> Queues { get; set; }
        public virtual User User { get; set; }
    }
}
