//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFConsoleServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DictionaryChangeHistory
    {
        public int DictionaryHistory_id { get; set; }
        public int UserHistory_id { get; set; }
        public int Dictionary_id { get; set; }
        public string Message { get; set; }
        public int Change_id { get; set; }
    
        public virtual ChangeType ChangeType { get; set; }
        public virtual Dictionary Dictionary { get; set; }
        public virtual UserChangeHistory UserChangeHistory { get; set; }
    }
}
