//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFConsoleServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictionary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dictionary()
        {
            this.Dictionary1 = new HashSet<Dictionary>();
            this.DictionaryChangeHistories = new HashSet<DictionaryChangeHistory>();
            this.DictionaryOnTasks = new HashSet<DictionaryOnTask>();
            this.Queues = new HashSet<Queue>();
            this.UserChangeHistories = new HashSet<UserChangeHistory>();
            this.Versions = new HashSet<Version>();
        }
    
        public int Dictionary_id { get; set; }
        public int Category_id { get; set; }
        public string Description { get; set; }
        public int State_id { get; set; }
        public string PathToDict { get; set; }
        public Nullable<System.DateTime> DateDel { get; set; }
        public Nullable<int> ParentDict_id { get; set; }
        public string FriendlyName { get; set; }
        public string FileName { get; set; }
    
        public virtual DictionaryCategory DictionaryCategory { get; set; }
        public virtual DictionaryState DictionaryState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dictionary> Dictionary1 { get; set; }
        public virtual Dictionary Dictionary2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DictionaryChangeHistory> DictionaryChangeHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DictionaryOnTask> DictionaryOnTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Queue> Queues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserChangeHistory> UserChangeHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Version> Versions { get; set; }
    }
}
